name: Build and Test Java Spring Boot Application 
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: B@nLgU4qz*9?D~3n83
          POSTGRES_DB: account
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    # Récupération du code
    - uses: actions/checkout@v3
    # paramétrage d'une JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # création de la structure de la base de données
    - name: Database creation
      # Attention aux caractères spéciaux dans l'URL utilisée pour la connexion
      # @ devient %40
      # * devient %2A
      # ? devient %3F
      # ~ devient %7E
      run: psql -f ./db/dump/1_db-creations.sql postgresql://postgres:B%40nLgU4qz%2A9%3FD%7E3n83@localhost:5432/account
    
    - name: Build with Maven
      run: mvn clean verify
 
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: SpringBoot Report               # nom du fichier
          path: target/site/orm/           # chemin vers les résultats
